### ISSUE TITLE
Change b/r configuration file format to YAML

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-afghanistan#9]
INI files have significant limitations, which forced to adopt solutions like to following to configure pairs of settings:

```
migrations = base.resourcebase,layers.layer,...
manglers   = gn24_to_24.ResourceBaseMangler,gn24_to_24.LayerMangler,....
```

which will parsed and "zipped" in Python code to obtain pairs of values.

This and other drawbacks with INI files suggest to upgrade the configuration of the backup and restore management commands to a YAML based configuration.
**Support for this new configuration format will be implemented for the management commands only**. 

I propose to adopt the following schema:

```
geonode:
    fixtures:
    - all:
       - contenttypes
       - auth
       - people
       - groups
       - base
       - documents
       - layers
       - maps
    - resources:
        - base
        - documents
        - layers
        - maps
    - users:
       - auth
       - people
       - groups

    backup:
       manglers:
       -  fixture: layers
          mangler: mymanglers.LayersMangler
    restore:
       manglers:
       -  fixture: layers
          mangler: mymanglers.LayersMangler
database:
  pgdump: pg_dump
  pgrestore: pg_restore
geoserver:
  datadir: geoserver/data
  dumpvectordata: yes
  dumprasterdata: yes
```

which will produce the following Python object:

```
{'database': {'pgdump': 'pg_dump', 'pgrestore': 'pg_restore'},
 'geonode': {'backup': {'manglers': [{'fixture': 'layers',
                                      'mangler': 'mymanglers.LayersMangler'}]},
             'fixtures': [{'all': ['contenttypes',
                                   'auth',
                                   'people',
                                   'groups',
                                   'base',
                                   'documents',
                                   'layers',
                                   'maps']},
                          {'resources': ['base',
                                         'documents',
                                         'layers',
                                         'maps']},
                          {'users': ['auth', 'people', 'groups']}],
             'restore': {'manglers': [{'fixture': 'layers',
                                       'mangler': 'mymanglers.LayersMangler'}]}},
 'geoserver': {'datadir': 'geoserver/data',
               'dumprasterdata': True,
               'dumpvectordata': True}}
```
 
Differences from current INI:

- fixtures can be grouped by "backup types". "all" might represent the dump of all the GN apps DB, "resources" for only documents, layers and maps, etc.
- removed "dumps" configuration. The name of the output file will be the same as the fixture app_name
- manglers are optionals and configurable both for backup and restore. Each mangler is a pair wtih the "fixture" value equal to one of the dumped fixtures, and "mangler" the dotted path to the mangler module
